# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/rzvejs/src/rendeng

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/rzvejs/src/rendeng

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rzvejs/src/rendeng/CMakeFiles /Users/rzvejs/src/rendeng//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rzvejs/src/rendeng/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vector

# Build rule for target.
vector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vector
.PHONY : vector

# fast build rule for target.
vector/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/build
.PHONY : vector/fast

#=============================================================================
# Target rules for targets named scene

# Build rule for target.
scene: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scene
.PHONY : scene

# fast build rule for target.
scene/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene.dir/build.make CMakeFiles/scene.dir/build
.PHONY : scene/fast

#=============================================================================
# Target rules for targets named objs

# Build rule for target.
objs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 objs
.PHONY : objs

# fast build rule for target.
objs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objs.dir/build.make CMakeFiles/objs.dir/build
.PHONY : objs/fast

#=============================================================================
# Target rules for targets named models

# Build rule for target.
models: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 models
.PHONY : models

# fast build rule for target.
models/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/models.dir/build.make CMakeFiles/models.dir/build
.PHONY : models/fast

#=============================================================================
# Target rules for targets named linalg

# Build rule for target.
linalg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linalg
.PHONY : linalg

# fast build rule for target.
linalg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linalg.dir/build.make CMakeFiles/linalg.dir/build
.PHONY : linalg/fast

#=============================================================================
# Target rules for targets named image

# Build rule for target.
image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 image
.PHONY : image

# fast build rule for target.
image/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/build
.PHONY : image/fast

#=============================================================================
# Target rules for targets named error

# Build rule for target.
error: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 error
.PHONY : error

# fast build rule for target.
error/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/error.dir/build.make CMakeFiles/error.dir/build
.PHONY : error/fast

#=============================================================================
# Target rules for targets named rendeng

# Build rule for target.
rendeng: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rendeng
.PHONY : rendeng

# fast build rule for target.
rendeng/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendeng.dir/build.make CMakeFiles/rendeng.dir/build
.PHONY : rendeng/fast

src/rendeng/error.o: src/rendeng/error.c.o
.PHONY : src/rendeng/error.o

# target to build an object file
src/rendeng/error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/error.dir/build.make CMakeFiles/error.dir/src/rendeng/error.c.o
.PHONY : src/rendeng/error.c.o

src/rendeng/error.i: src/rendeng/error.c.i
.PHONY : src/rendeng/error.i

# target to preprocess a source file
src/rendeng/error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/error.dir/build.make CMakeFiles/error.dir/src/rendeng/error.c.i
.PHONY : src/rendeng/error.c.i

src/rendeng/error.s: src/rendeng/error.c.s
.PHONY : src/rendeng/error.s

# target to generate assembly for a file
src/rendeng/error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/error.dir/build.make CMakeFiles/error.dir/src/rendeng/error.c.s
.PHONY : src/rendeng/error.c.s

src/rendeng/image.o: src/rendeng/image.c.o
.PHONY : src/rendeng/image.o

# target to build an object file
src/rendeng/image.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/src/rendeng/image.c.o
.PHONY : src/rendeng/image.c.o

src/rendeng/image.i: src/rendeng/image.c.i
.PHONY : src/rendeng/image.i

# target to preprocess a source file
src/rendeng/image.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/src/rendeng/image.c.i
.PHONY : src/rendeng/image.c.i

src/rendeng/image.s: src/rendeng/image.c.s
.PHONY : src/rendeng/image.s

# target to generate assembly for a file
src/rendeng/image.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/src/rendeng/image.c.s
.PHONY : src/rendeng/image.c.s

src/rendeng/linalg.o: src/rendeng/linalg.c.o
.PHONY : src/rendeng/linalg.o

# target to build an object file
src/rendeng/linalg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linalg.dir/build.make CMakeFiles/linalg.dir/src/rendeng/linalg.c.o
.PHONY : src/rendeng/linalg.c.o

src/rendeng/linalg.i: src/rendeng/linalg.c.i
.PHONY : src/rendeng/linalg.i

# target to preprocess a source file
src/rendeng/linalg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linalg.dir/build.make CMakeFiles/linalg.dir/src/rendeng/linalg.c.i
.PHONY : src/rendeng/linalg.c.i

src/rendeng/linalg.s: src/rendeng/linalg.c.s
.PHONY : src/rendeng/linalg.s

# target to generate assembly for a file
src/rendeng/linalg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linalg.dir/build.make CMakeFiles/linalg.dir/src/rendeng/linalg.c.s
.PHONY : src/rendeng/linalg.c.s

src/rendeng/main.o: src/rendeng/main.c.o
.PHONY : src/rendeng/main.o

# target to build an object file
src/rendeng/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendeng.dir/build.make CMakeFiles/rendeng.dir/src/rendeng/main.c.o
.PHONY : src/rendeng/main.c.o

src/rendeng/main.i: src/rendeng/main.c.i
.PHONY : src/rendeng/main.i

# target to preprocess a source file
src/rendeng/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendeng.dir/build.make CMakeFiles/rendeng.dir/src/rendeng/main.c.i
.PHONY : src/rendeng/main.c.i

src/rendeng/main.s: src/rendeng/main.c.s
.PHONY : src/rendeng/main.s

# target to generate assembly for a file
src/rendeng/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendeng.dir/build.make CMakeFiles/rendeng.dir/src/rendeng/main.c.s
.PHONY : src/rendeng/main.c.s

src/rendeng/models.o: src/rendeng/models.c.o
.PHONY : src/rendeng/models.o

# target to build an object file
src/rendeng/models.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/models.dir/build.make CMakeFiles/models.dir/src/rendeng/models.c.o
.PHONY : src/rendeng/models.c.o

src/rendeng/models.i: src/rendeng/models.c.i
.PHONY : src/rendeng/models.i

# target to preprocess a source file
src/rendeng/models.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/models.dir/build.make CMakeFiles/models.dir/src/rendeng/models.c.i
.PHONY : src/rendeng/models.c.i

src/rendeng/models.s: src/rendeng/models.c.s
.PHONY : src/rendeng/models.s

# target to generate assembly for a file
src/rendeng/models.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/models.dir/build.make CMakeFiles/models.dir/src/rendeng/models.c.s
.PHONY : src/rendeng/models.c.s

src/rendeng/objs.o: src/rendeng/objs.c.o
.PHONY : src/rendeng/objs.o

# target to build an object file
src/rendeng/objs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objs.dir/build.make CMakeFiles/objs.dir/src/rendeng/objs.c.o
.PHONY : src/rendeng/objs.c.o

src/rendeng/objs.i: src/rendeng/objs.c.i
.PHONY : src/rendeng/objs.i

# target to preprocess a source file
src/rendeng/objs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objs.dir/build.make CMakeFiles/objs.dir/src/rendeng/objs.c.i
.PHONY : src/rendeng/objs.c.i

src/rendeng/objs.s: src/rendeng/objs.c.s
.PHONY : src/rendeng/objs.s

# target to generate assembly for a file
src/rendeng/objs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objs.dir/build.make CMakeFiles/objs.dir/src/rendeng/objs.c.s
.PHONY : src/rendeng/objs.c.s

src/rendeng/scene.o: src/rendeng/scene.c.o
.PHONY : src/rendeng/scene.o

# target to build an object file
src/rendeng/scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene.dir/build.make CMakeFiles/scene.dir/src/rendeng/scene.c.o
.PHONY : src/rendeng/scene.c.o

src/rendeng/scene.i: src/rendeng/scene.c.i
.PHONY : src/rendeng/scene.i

# target to preprocess a source file
src/rendeng/scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene.dir/build.make CMakeFiles/scene.dir/src/rendeng/scene.c.i
.PHONY : src/rendeng/scene.c.i

src/rendeng/scene.s: src/rendeng/scene.c.s
.PHONY : src/rendeng/scene.s

# target to generate assembly for a file
src/rendeng/scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scene.dir/build.make CMakeFiles/scene.dir/src/rendeng/scene.c.s
.PHONY : src/rendeng/scene.c.s

src/vector.o: src/vector.c.o
.PHONY : src/vector.o

# target to build an object file
src/vector.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/src/vector.c.o
.PHONY : src/vector.c.o

src/vector.i: src/vector.c.i
.PHONY : src/vector.i

# target to preprocess a source file
src/vector.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/src/vector.c.i
.PHONY : src/vector.c.i

src/vector.s: src/vector.c.s
.PHONY : src/vector.s

# target to generate assembly for a file
src/vector.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/src/vector.c.s
.PHONY : src/vector.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... error"
	@echo "... image"
	@echo "... linalg"
	@echo "... models"
	@echo "... objs"
	@echo "... rendeng"
	@echo "... scene"
	@echo "... vector"
	@echo "... src/rendeng/error.o"
	@echo "... src/rendeng/error.i"
	@echo "... src/rendeng/error.s"
	@echo "... src/rendeng/image.o"
	@echo "... src/rendeng/image.i"
	@echo "... src/rendeng/image.s"
	@echo "... src/rendeng/linalg.o"
	@echo "... src/rendeng/linalg.i"
	@echo "... src/rendeng/linalg.s"
	@echo "... src/rendeng/main.o"
	@echo "... src/rendeng/main.i"
	@echo "... src/rendeng/main.s"
	@echo "... src/rendeng/models.o"
	@echo "... src/rendeng/models.i"
	@echo "... src/rendeng/models.s"
	@echo "... src/rendeng/objs.o"
	@echo "... src/rendeng/objs.i"
	@echo "... src/rendeng/objs.s"
	@echo "... src/rendeng/scene.o"
	@echo "... src/rendeng/scene.i"
	@echo "... src/rendeng/scene.s"
	@echo "... src/vector.o"
	@echo "... src/vector.i"
	@echo "... src/vector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

